// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"fmt"
	"io"
	"strconv"
)

type ApplicationHTTP struct {
	ID                            string `json:"id"`
	CreatedAt                     string `json:"createdAt"`
	UpdatedAt                     string `json:"updatedAt"`
	AuthorID                      string `json:"authorId"`
	Nomination                    string `json:"nomination"`
	AlgorithmicTaskLink           string `json:"algorithmicTaskLink"`
	AlgorithmicTaskFile           string `json:"algorithmicTaskFile"`
	CreativeTaskLink              string `json:"creativeTaskLink"`
	CreativeTaskFile              string `json:"creativeTaskFile"`
	EngineeringTaskFile           string `json:"engineeringTaskFile"`
	EngineeringTaskCloudLink      string `json:"engineeringTaskCloudLink"`
	EngineeringTaskVideo          string `json:"engineeringTaskVideo"`
	EngineeringTaskVideoCloudLink string `json:"engineeringTaskVideoCloudLink"`
	Note                          string `json:"note"`
}

type ApplicationHTTPList struct {
	Applications []*ApplicationHTTP `json:"applications"`
	CountRows    int                `json:"countRows"`
}

type CountryHTTP struct {
	ID         string `json:"id"`
	CreatedAt  string `json:"createdAt"`
	UpdatedAt  string `json:"updatedAt"`
	Name       string `json:"name"`
	HasRegions bool   `json:"hasRegions"`
}

type CountryHTTPList struct {
	Countries []*CountryHTTP `json:"countries"`
	CountRows int            `json:"countRows"`
}

type EventDetailsHTTP struct {
	ID          string                `json:"id"`
	CreatedAt   string                `json:"createdAt"`
	UpdatedAt   string                `json:"updatedAt"`
	Name        string                `json:"name"`
	Description string                `json:"description"`
	StartDate   string                `json:"startDate"`
	EndDate     string                `json:"endDate"`
	Translation *EventTranslationHTTP `json:"translation,omitempty"`
}

type EventHTTP struct {
	ID        string `json:"id"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	Name      string `json:"name"`
	StartDate string `json:"startDate"`
	EndDate   string `json:"endDate"`
}

type EventHTTPList struct {
	Events    []*EventHTTP `json:"events"`
	CountRows int          `json:"countRows"`
}

type EventRoleList struct {
	Roles []EventRole `json:"roles"`
}

type EventTranslationHTTP struct {
	ID          string `json:"id"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
	Name        string `json:"name"`
	Description string `json:"description"`
	EventID     string `json:"eventId"`
}

type NewApplication struct {
	Nomination                    string  `json:"nomination"`
	AlgorithmicTaskLink           *string `json:"algorithmicTaskLink,omitempty"`
	AlgorithmicTaskFile           *string `json:"algorithmicTaskFile,omitempty"`
	CreativeTaskLink              *string `json:"creativeTaskLink,omitempty"`
	CreativeTaskFile              *string `json:"creativeTaskFile,omitempty"`
	EngineeringTaskFile           *string `json:"engineeringTaskFile,omitempty"`
	EngineeringTaskCloudLink      *string `json:"engineeringTaskCloudLink,omitempty"`
	EngineeringTaskVideo          *string `json:"engineeringTaskVideo,omitempty"`
	EngineeringTaskVideoCloudLink *string `json:"engineeringTaskVideoCloudLink,omitempty"`
	Note                          *string `json:"note,omitempty"`
}

type NewEvent struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	StartDate   string `json:"startDate"`
	EndDate     string `json:"endDate"`
}

type NewEventTranslation struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	EventID     string `json:"eventId"`
}

type NewUser struct {
	Email          string  `json:"email"`
	Password       string  `json:"password"`
	Role           Role    `json:"role"`
	FullName       string  `json:"fullName"`
	FullNameNative string  `json:"fullNameNative"`
	CountryID      string  `json:"countryId"`
	RegionID       *string `json:"regionId,omitempty"`
	City           string  `json:"city"`
	Birthdate      string  `json:"birthdate"`
}

type NewUserResponse struct {
	ID             string  `json:"id"`
	Email          string  `json:"email"`
	Role           int     `json:"role"`
	FullName       string  `json:"fullName"`
	FullNameNative string  `json:"fullNameNative"`
	CountryID      string  `json:"countryId"`
	RegionID       *string `json:"regionId,omitempty"`
	City           string  `json:"city"`
	Birthdate      string  `json:"birthdate"`
}

type NominationHTTP struct {
	ID        string `json:"id"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	Name      string `json:"name"`
	MinAge    int    `json:"minAge"`
	MaxAge    int    `json:"maxAge"`
}

type NominationHTTPList struct {
	Nominations []*NominationHTTP `json:"nominations"`
	CountRows   int               `json:"countRows"`
}

type RegionHTTP struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CountryID string `json:"countryId"`
}

type RegionHTTPList struct {
	Regions   []*RegionHTTP `json:"regions"`
	CountRows int           `json:"countRows"`
}

type Response struct {
	Ok bool `json:"ok"`
}

type Settings struct {
	ActivationByLink bool `json:"activationByLink"`
}

type SignIn struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignInResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type SignUp struct {
	Email          string  `json:"email"`
	Password       string  `json:"password"`
	FullName       string  `json:"fullName"`
	FullNameNative string  `json:"fullNameNative"`
	CountryID      string  `json:"countryId"`
	RegionID       *string `json:"regionId,omitempty"`
	City           string  `json:"city"`
	Birthdate      string  `json:"birthdate"`
}

type UpdateEvent struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	StartDate   string `json:"startDate"`
	EndDate     string `json:"endDate"`
}

type UpdateEventTranslation struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type UpdateUser struct {
	ID             string  `json:"id"`
	Email          string  `json:"email"`
	FullName       string  `json:"fullName"`
	FullNameNative string  `json:"fullNameNative"`
	CountryID      string  `json:"countryId"`
	RegionID       *string `json:"regionId,omitempty"`
	City           string  `json:"city"`
	Birthdate      string  `json:"birthdate"`
}

type UserHTTP struct {
	ID             string       `json:"id"`
	CreatedAt      string       `json:"createdAt"`
	UpdatedAt      string       `json:"updatedAt"`
	Email          string       `json:"email"`
	Password       string       `json:"password"`
	Role           Role         `json:"role"`
	FullName       string       `json:"fullName"`
	FullNameNative string       `json:"fullNameNative"`
	Country        *CountryHTTP `json:"country"`
	Region         *RegionHTTP  `json:"region,omitempty"`
	City           string       `json:"city"`
	Birthdate      string       `json:"birthdate"`
	IsActive       bool         `json:"isActive"`
}

type UsersList struct {
	Users     []*UserHTTP `json:"users"`
	CountRows int         `json:"countRows"`
}

type EventRole string

const (
	EventRoleOrganizer EventRole = "Organizer"
	EventRoleModerator EventRole = "Moderator"
	EventRoleExpert    EventRole = "Expert"
)

var AllEventRole = []EventRole{
	EventRoleOrganizer,
	EventRoleModerator,
	EventRoleExpert,
}

func (e EventRole) IsValid() bool {
	switch e {
	case EventRoleOrganizer, EventRoleModerator, EventRoleExpert:
		return true
	}
	return false
}

func (e EventRole) String() string {
	return string(e)
}

func (e *EventRole) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EventRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EventRole", str)
	}
	return nil
}

func (e EventRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Role string

const (
	RoleAnonymous  Role = "Anonymous"
	RoleUser       Role = "User"
	RoleAdmin      Role = "Admin"
	RoleSuperAdmin Role = "SuperAdmin"
)

var AllRole = []Role{
	RoleAnonymous,
	RoleUser,
	RoleAdmin,
	RoleSuperAdmin,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAnonymous, RoleUser, RoleAdmin, RoleSuperAdmin:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
