input SignUp {
	email: String!
	password: String!
	fullName: String!
	fullNameNative: String!
	countryId: ID!
	regionId: ID
	city: String!
	birthdate: Timestamp!
}

input SignIn {
	email: String!
	password: String!
}

type SignInResponse {
	accessToken: String!
	refreshToken: String!
}

extend type Query {
	Me: UserHttp! @hasRole(roles:[SuperAdmin, Admin, User])
}

extend type Mutation  {
	SignUp(input: SignUp!): Response!
	SignIn(input: SignIn!): SignInResponse!
	RefreshToken(refreshToken: String!): SignInResponse!
	ConfirmActivation(activationToken: String!): SignInResponse!
	ForgotPassword(email: String!): Response!
	ResetPassword(resetToken: String!): Response!
}