
extend type Mutation {
    SetOrganizerForEvent(eventId: ID!, userId: ID!): Response! @hasRole(roles: [SuperAdmin, Admin])
    SetModeratorForEvent(eventId: ID!, userId: ID!): Response! @hasRole(roles: [SuperAdmin, Admin, User])
    SetExpertForEvent(eventId: ID!, userId: ID!): Response! @hasRole(roles: [SuperAdmin, Admin, User])

    UnsetOrganizerForEvent(eventId: ID!, userId: ID!): Response! @hasRole(roles: [SuperAdmin, Admin])
    UnsetModeratorForEvent(eventId: ID!, userId: ID!): Response! @hasRole(roles: [SuperAdmin, Admin, User])
    UnsetExpertForEvent(eventId: ID!, userId: ID!): Response! @hasRole(roles: [SuperAdmin, Admin, User])
}