type EventHttp {
    id: ID!
    createdAt: Timestamp!
    updatedAt: Timestamp!
    name: String!
    startDate: Timestamp!
    endDate: Timestamp!
}

type EventDetailsHttp {
    id: ID!
    createdAt: Timestamp!
    updatedAt: Timestamp!
    name: String!
    description: String!
    startDate: Timestamp!
    endDate: Timestamp!
    translation: EventTranslationHttp
}

input NewEvent {
    name: String!
    description: String!
    startDate: Timestamp!
    endDate: Timestamp!
}

input UpdateEvent {
    id: ID!
    name: String!
    description: String!
    startDate: Timestamp!
    endDate: Timestamp!
}

type EventHttpList {
    events: [EventHttp!]!
    countRows: Int!
}

extend type Query {
    GetEventById(id: ID!): EventDetailsHttp! @hasRole(roles: [SuperAdmin, Admin, User])
    GetAllEvents(page: Int, pageSize: Int): EventHttpList! @hasRole(roles: [SuperAdmin, Admin, User])
}

extend type Mutation {
    CreateEvent(input: NewEvent!): EventDetailsHttp! @hasRole(roles: [SuperAdmin, Admin])
    UpdateEvent(input: UpdateEvent!): EventDetailsHttp! @hasRole(roles: [SuperAdmin, Admin, User])
}