package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"
	"net/http"
	"strconv"
	"time"

	"github.com/robboworld/scratch_olympiad_platform/internal/consts"
	"github.com/robboworld/scratch_olympiad_platform/internal/models"
	"github.com/robboworld/scratch_olympiad_platform/pkg/utils"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateEvent is the resolver for the CreateEvent field.
func (r *mutationResolver) CreateEvent(ctx context.Context, input models.NewEvent) (*models.EventDetailsHTTP, error) {
	startDate, err := time.Parse(time.DateOnly, input.StartDate)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrTimeParse,
				},
			},
		}
	}
	endDate, err := time.Parse(time.DateOnly, input.EndDate)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrTimeParse,
				},
			},
		}
	}
	event := models.EventCore{
		Name:        input.Name,
		StartDate:   startDate,
		EndDate:     endDate,
		Description: input.Description,
	}

	newEvent, err := r.eventService.CreateEvent(event)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}

	eventHttp := models.EventDetailsHTTP{}
	eventHttp.FromCore(newEvent)
	return &eventHttp, nil
}

// UpdateEvent is the resolver for the UpdateEvent field.
func (r *mutationResolver) UpdateEvent(ctx context.Context, input models.UpdateEvent) (*models.EventDetailsHTTP, error) {
	atoi, err := strconv.Atoi(input.ID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	startDate, err := time.Parse(time.DateOnly, input.StartDate)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrTimeParse,
				},
			},
		}
	}
	endDate, err := time.Parse(time.DateOnly, input.EndDate)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrTimeParse,
				},
			},
		}
	}
	event := models.EventCore{
		ID:          uint(atoi),
		Name:        input.Name,
		Description: input.Description,
		StartDate:   startDate,
		EndDate:     endDate,
	}
	updatedEvent, err := r.eventService.UpdateEvent(event)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	eventHttp := models.EventDetailsHTTP{}
	eventHttp.FromCore(updatedEvent)
	return &eventHttp, nil
}

// CreateEventTranslation is the resolver for the CreateEventTranslation field.
func (r *mutationResolver) CreateEventTranslation(ctx context.Context, input models.NewEventTranslation) (*models.EventTranslationHTTP, error) {
	ginContext, err := utils.GinContextFromContext(ctx)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	clientId := ginContext.Value(consts.KeyId).(uint)
	clientRole := ginContext.Value(consts.KeyRole).(models.Role)
	eventIdInt, err := strconv.Atoi(input.EventID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	eventTranslation := models.EventTranslationCore{
		Name:        input.Name,
		Description: input.Description,
		EventID:     uint(eventIdInt),
	}
	newEventTranslation, err := r.eventTranslationService.CreateEventTranslation(eventTranslation, clientId, clientRole)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	newEventTranslationHttp := models.EventTranslationHTTP{}
	newEventTranslationHttp.FromCore(newEventTranslation)
	return &newEventTranslationHttp, nil
}

// UpdateEventTranslation is the resolver for the UpdateEventTranslation field.
func (r *mutationResolver) UpdateEventTranslation(ctx context.Context, input models.UpdateEventTranslation) (*models.EventTranslationHTTP, error) {
	ginContext, err := utils.GinContextFromContext(ctx)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	clientId := ginContext.Value(consts.KeyId).(uint)
	clientRole := ginContext.Value(consts.KeyRole).(models.Role)
	atoi, err := strconv.Atoi(input.ID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	eventTranslation := models.EventTranslationCore{
		ID:          uint(atoi),
		Name:        input.Name,
		Description: input.Description,
	}
	updatedEventTranslation, err := r.eventTranslationService.UpdateEventTranslation(eventTranslation, clientId, clientRole)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	updatedEventTranslationHttp := models.EventTranslationHTTP{}
	updatedEventTranslationHttp.FromCore(updatedEventTranslation)
	return &updatedEventTranslationHttp, nil
}

// DeleteEventTranslation is the resolver for the DeleteEventTranslation field.
func (r *mutationResolver) DeleteEventTranslation(ctx context.Context, id string) (*models.Response, error) {
	ginContext, err := utils.GinContextFromContext(ctx)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	clientId := ginContext.Value(consts.KeyId).(uint)
	clientRole := ginContext.Value(consts.KeyRole).(models.Role)
	atoi, err := strconv.Atoi(id)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	err = r.eventTranslationService.DeleteEventTranslation(uint(atoi), clientId, clientRole)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return &models.Response{Ok: false}, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	return &models.Response{Ok: true}, nil
}

// SetOrganizerForEvent is the resolver for the SetOrganizerForEvent field.
func (r *mutationResolver) SetOrganizerForEvent(ctx context.Context, eventID string, userID string) (*models.Response, error) {
	ginContext, err := utils.GinContextFromContext(ctx)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	clientId := ginContext.Value(consts.KeyId).(uint)
	clientRole := ginContext.Value(consts.KeyRole).(models.Role)
	eventIdInt, err := strconv.Atoi(eventID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	userIdInt, err := strconv.Atoi(userID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	err = r.eventUserService.SetOrganizerForEvent(uint(eventIdInt), uint(userIdInt), clientId, clientRole)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return &models.Response{Ok: false}, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	return &models.Response{Ok: true}, nil
}

// SetModeratorForEvent is the resolver for the SetModeratorForEvent field.
func (r *mutationResolver) SetModeratorForEvent(ctx context.Context, eventID string, userID string) (*models.Response, error) {
	ginContext, err := utils.GinContextFromContext(ctx)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	clientId := ginContext.Value(consts.KeyId).(uint)
	clientRole := ginContext.Value(consts.KeyRole).(models.Role)
	eventIdInt, err := strconv.Atoi(eventID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	userIdInt, err := strconv.Atoi(userID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	err = r.eventUserService.SetModeratorForEvent(uint(eventIdInt), uint(userIdInt), clientId, clientRole)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return &models.Response{Ok: false}, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	return &models.Response{Ok: true}, nil
}

// SetExpertForEvent is the resolver for the SetExpertForEvent field.
func (r *mutationResolver) SetExpertForEvent(ctx context.Context, eventID string, userID string) (*models.Response, error) {
	ginContext, err := utils.GinContextFromContext(ctx)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	clientId := ginContext.Value(consts.KeyId).(uint)
	clientRole := ginContext.Value(consts.KeyRole).(models.Role)
	eventIdInt, err := strconv.Atoi(eventID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	userIdInt, err := strconv.Atoi(userID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	err = r.eventUserService.SetExpertForEvent(uint(eventIdInt), uint(userIdInt), clientId, clientRole)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return &models.Response{Ok: false}, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	return &models.Response{Ok: true}, nil
}

// SetCountryForEvent is the resolver for the SetCountryForEvent field.
func (r *mutationResolver) SetCountryForEvent(ctx context.Context, eventID string, countryID string) (*models.Response, error) {
	ginContext, err := utils.GinContextFromContext(ctx)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	clientRole := ginContext.Value(consts.KeyRole).(models.Role)
	eventIdInt, err := strconv.Atoi(eventID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	countryIdInt, err := strconv.Atoi(countryID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	err = r.eventCountryService.SetCountryForEvent(uint(eventIdInt), uint(countryIdInt), clientRole)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return &models.Response{Ok: false}, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	return &models.Response{Ok: true}, nil
}

// SetRegionForEvent is the resolver for the SetRegionForEvent field.
func (r *mutationResolver) SetRegionForEvent(ctx context.Context, eventID string, regionID string) (*models.Response, error) {
	ginContext, err := utils.GinContextFromContext(ctx)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	clientRole := ginContext.Value(consts.KeyRole).(models.Role)
	eventIdInt, err := strconv.Atoi(eventID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	regionIdInt, err := strconv.Atoi(regionID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	err = r.eventRegionService.SetRegionForEvent(uint(eventIdInt), uint(regionIdInt), clientRole)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return &models.Response{Ok: false}, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	return &models.Response{Ok: true}, nil
}

// UnsetOrganizerForEvent is the resolver for the UnsetOrganizerForEvent field.
func (r *mutationResolver) UnsetOrganizerForEvent(ctx context.Context, eventID string, userID string) (*models.Response, error) {
	ginContext, err := utils.GinContextFromContext(ctx)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	clientRole := ginContext.Value(consts.KeyRole).(models.Role)
	eventIdInt, err := strconv.Atoi(eventID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	userIdInt, err := strconv.Atoi(userID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	err = r.eventUserService.UnsetOrganizerForEvent(uint(eventIdInt), uint(userIdInt), clientRole)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return &models.Response{Ok: false}, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	return &models.Response{Ok: true}, nil
}

// UnsetModeratorForEvent is the resolver for the UnsetModeratorForEvent field.
func (r *mutationResolver) UnsetModeratorForEvent(ctx context.Context, eventID string, userID string) (*models.Response, error) {
	ginContext, err := utils.GinContextFromContext(ctx)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	clientId := ginContext.Value(consts.KeyId).(uint)
	clientRole := ginContext.Value(consts.KeyRole).(models.Role)
	eventIdInt, err := strconv.Atoi(eventID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	userIdInt, err := strconv.Atoi(userID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	err = r.eventUserService.UnsetModeratorForEvent(uint(eventIdInt), uint(userIdInt), clientId, clientRole)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return &models.Response{Ok: false}, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	return &models.Response{Ok: true}, nil
}

// UnsetExpertForEvent is the resolver for the UnsetExpertForEvent field.
func (r *mutationResolver) UnsetExpertForEvent(ctx context.Context, eventID string, userID string) (*models.Response, error) {
	ginContext, err := utils.GinContextFromContext(ctx)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	clientId := ginContext.Value(consts.KeyId).(uint)
	clientRole := ginContext.Value(consts.KeyRole).(models.Role)
	eventIdInt, err := strconv.Atoi(eventID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	userIdInt, err := strconv.Atoi(userID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	err = r.eventUserService.UnsetExpertForEvent(uint(eventIdInt), uint(userIdInt), clientId, clientRole)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return &models.Response{Ok: false}, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	return &models.Response{Ok: true}, nil
}

// UnsetCountryForEvent is the resolver for the UnsetCountryForEvent field.
func (r *mutationResolver) UnsetCountryForEvent(ctx context.Context, eventID string, countryID string) (*models.Response, error) {
	ginContext, err := utils.GinContextFromContext(ctx)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	clientRole := ginContext.Value(consts.KeyRole).(models.Role)
	eventIdInt, err := strconv.Atoi(eventID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	countryIdInt, err := strconv.Atoi(countryID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	err = r.eventCountryService.UnsetCountryForEvent(uint(eventIdInt), uint(countryIdInt), clientRole)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return &models.Response{Ok: false}, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	return &models.Response{Ok: true}, nil
}

// UnsetRegionForEvent is the resolver for the UnsetRegionForEvent field.
func (r *mutationResolver) UnsetRegionForEvent(ctx context.Context, eventID string, regionID string) (*models.Response, error) {
	ginContext, err := utils.GinContextFromContext(ctx)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	clientRole := ginContext.Value(consts.KeyRole).(models.Role)
	eventIdInt, err := strconv.Atoi(eventID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	regionIdInt, err := strconv.Atoi(regionID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	err = r.eventRegionService.UnsetRegionForEvent(uint(eventIdInt), uint(regionIdInt), clientRole)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return &models.Response{Ok: false}, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	return &models.Response{Ok: true}, nil
}

// GetEventByID is the resolver for the GetEventById field.
func (r *queryResolver) GetEventByID(ctx context.Context, id string) (*models.EventDetailsHTTP, error) {
	ginContext, err := utils.GinContextFromContext(ctx)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	clientId := ginContext.Value(consts.KeyId).(uint)
	clientRole := ginContext.Value(consts.KeyRole).(models.Role)
	atoi, err := strconv.Atoi(id)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	event, err := r.eventService.GetEventById(uint(atoi), clientId, clientRole)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	eventHttp := models.EventDetailsHTTP{}
	eventHttp.FromCore(event)
	return &eventHttp, nil
}

// GetAllEvents is the resolver for the GetAllEvents field.
func (r *queryResolver) GetAllEvents(ctx context.Context, page *int, pageSize *int) (*models.EventHTTPList, error) {
	ginContext, err := utils.GinContextFromContext(ctx)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	clientId := ginContext.Value(consts.KeyId).(uint)
	clientRole := ginContext.Value(consts.KeyRole).(models.Role)
	events, countRows, err := r.eventService.GetAllEvents(page, pageSize, clientId, clientRole)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	return &models.EventHTTPList{
		Events:    models.FromEventsCore(events),
		CountRows: int(countRows),
	}, nil
}

// GetEventTranslationByEventID is the resolver for the GetEventTranslationByEventId field.
func (r *queryResolver) GetEventTranslationByEventID(ctx context.Context, eventID string) (*models.EventTranslationHTTP, error) {
	ginContext, err := utils.GinContextFromContext(ctx)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	clientId := ginContext.Value(consts.KeyId).(uint)
	clientRole := ginContext.Value(consts.KeyRole).(models.Role)
	eventIdInt, err := strconv.Atoi(eventID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	eventTranslation, err := r.eventTranslationService.GetEventTranslationByEventId(uint(eventIdInt), clientId, clientRole)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	eventTranslationHttp := models.EventTranslationHTTP{}
	eventTranslationHttp.FromCore(eventTranslation)
	return &eventTranslationHttp, nil
}

// GetEventRolesByAccessToken is the resolver for the GetEventRolesByAccessToken field.
func (r *queryResolver) GetEventRolesByAccessToken(ctx context.Context, eventID string) (*models.EventRoleList, error) {
	ginContext, err := utils.GinContextFromContext(ctx)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	clientId := ginContext.Value(consts.KeyId).(uint)
	eventIdInt, err := strconv.Atoi(eventID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	eventRoles, err := r.eventUserService.GetEventRoles(uint(eventIdInt), clientId)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	return &models.EventRoleList{
		Roles: eventRoles,
	}, nil
}
