package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"
	"net/http"
	"strconv"

	"github.com/robboworld/scratch_olympiad_platform/internal/consts"
	"github.com/robboworld/scratch_olympiad_platform/internal/models"
	"github.com/robboworld/scratch_olympiad_platform/pkg/utils"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateEventTranslation is the resolver for the CreateEventTranslation field.
func (r *mutationResolver) CreateEventTranslation(ctx context.Context, input models.NewEventTranslation) (*models.EventTranslationHTTP, error) {
	ginContext, err := utils.GinContextFromContext(ctx)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	clientId := ginContext.Value(consts.KeyId).(uint)
	clientRole := ginContext.Value(consts.KeyRole).(models.Role)
	eventIdInt, err := strconv.Atoi(input.EventID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	eventTranslation := models.EventTranslationCore{
		Name:        input.Name,
		Description: input.Description,
		EventID:     uint(eventIdInt),
	}
	newEventTranslation, err := r.eventTranslationService.CreateEventTranslation(eventTranslation, clientId, clientRole)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	newEventTranslationHttp := models.EventTranslationHTTP{}
	newEventTranslationHttp.FromCore(newEventTranslation)
	return &newEventTranslationHttp, nil
}

// UpdateEventTranslation is the resolver for the UpdateEventTranslation field.
func (r *mutationResolver) UpdateEventTranslation(ctx context.Context, input models.UpdateEventTranslation) (*models.EventTranslationHTTP, error) {
	ginContext, err := utils.GinContextFromContext(ctx)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	clientId := ginContext.Value(consts.KeyId).(uint)
	clientRole := ginContext.Value(consts.KeyRole).(models.Role)
	atoi, err := strconv.Atoi(input.ID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	eventTranslation := models.EventTranslationCore{
		ID:          uint(atoi),
		Name:        input.Name,
		Description: input.Description,
	}
	updatedEventTranslation, err := r.eventTranslationService.UpdateEventTranslation(eventTranslation, clientId, clientRole)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	updatedEventTranslationHttp := models.EventTranslationHTTP{}
	updatedEventTranslationHttp.FromCore(updatedEventTranslation)
	return &updatedEventTranslationHttp, nil
}

// DeleteEventTranslation is the resolver for the DeleteEventTranslation field.
func (r *mutationResolver) DeleteEventTranslation(ctx context.Context, id string) (*models.Response, error) {
	ginContext, err := utils.GinContextFromContext(ctx)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	clientId := ginContext.Value(consts.KeyId).(uint)
	clientRole := ginContext.Value(consts.KeyRole).(models.Role)
	atoi, err := strconv.Atoi(id)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	err = r.eventTranslationService.DeleteEventTranslation(uint(atoi), clientId, clientRole)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return &models.Response{Ok: false}, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	return &models.Response{Ok: true}, nil
}
