package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"
	"net/http"
	"strconv"
	"time"

	"github.com/robboworld/scratch_olympiad_platform/internal/consts"
	"github.com/robboworld/scratch_olympiad_platform/internal/models"
	"github.com/robboworld/scratch_olympiad_platform/pkg/utils"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateEvent is the resolver for the CreateEvent field.
func (r *mutationResolver) CreateEvent(ctx context.Context, input models.NewEvent) (*models.EventDetailsHTTP, error) {
	startDate, err := time.Parse(time.DateOnly, input.StartDate)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrTimeParse,
				},
			},
		}
	}
	endDate, err := time.Parse(time.DateOnly, input.EndDate)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrTimeParse,
				},
			},
		}
	}
	event := models.EventCore{
		Name:        input.Name,
		StartDate:   startDate,
		EndDate:     endDate,
		Description: input.Description,
	}

	newEvent, err := r.eventService.CreateEvent(event)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}

	eventHttp := models.EventDetailsHTTP{}
	eventHttp.FromCore(newEvent)
	return &eventHttp, nil
}

// UpdateEvent is the resolver for the UpdateEvent field.
func (r *mutationResolver) UpdateEvent(ctx context.Context, input models.UpdateEvent) (*models.EventDetailsHTTP, error) {
	atoi, err := strconv.Atoi(input.ID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	startDate, err := time.Parse(time.DateOnly, input.StartDate)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrTimeParse,
				},
			},
		}
	}
	endDate, err := time.Parse(time.DateOnly, input.EndDate)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrTimeParse,
				},
			},
		}
	}
	event := models.EventCore{
		ID:          uint(atoi),
		Name:        input.Name,
		Description: input.Description,
		StartDate:   startDate,
		EndDate:     endDate,
	}
	updatedEvent, err := r.eventService.UpdateEvent(event)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	eventHttp := models.EventDetailsHTTP{}
	eventHttp.FromCore(updatedEvent)
	return &eventHttp, nil
}

// GetEventByID is the resolver for the GetEventById field.
func (r *queryResolver) GetEventByID(ctx context.Context, id string) (*models.EventDetailsHTTP, error) {
	atoi, err := strconv.Atoi(id)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}
	event, err := r.eventService.GetEventById(uint(atoi))
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	eventHttp := models.EventDetailsHTTP{}
	eventHttp.FromCore(event)
	return &eventHttp, nil
}

// GetAllEvents is the resolver for the GetAllEvents field.
func (r *queryResolver) GetAllEvents(ctx context.Context, page *int, pageSize *int) (*models.EventHTTPList, error) {
	events, countRows, err := r.eventService.GetAllEvents(page, pageSize)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	return &models.EventHTTPList{
		Events:    models.FromEventsCore(events),
		CountRows: int(countRows),
	}, nil
}
