package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"
	"github.com/vektah/gqlparser/v2/gqlerror"

	"github.com/robboworld/scratch_olympiad_platform/internal/models"
)

// GetAllNominations is the resolver for the GetAllNominations field.
func (r *queryResolver) GetAllNominations(ctx context.Context, page *int, pageSize *int) (*models.NominationHTTPList, error) {
	nominations, countRows, err := r.nominationService.GetAllNominations(page, pageSize)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	return &models.NominationHTTPList{
		Nominations: models.FromNominationsCore(nominations),
		CountRows:   int(countRows),
	}, nil
}
