package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"
	"net/http"
	"strconv"

	"github.com/robboworld/scratch_olympiad_platform/internal/consts"
	"github.com/robboworld/scratch_olympiad_platform/internal/models"
	"github.com/robboworld/scratch_olympiad_platform/pkg/utils"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// GetRegionsByCountryID is the resolver for the GetRegionsByCountryId field.
func (r *queryResolver) GetRegionsByCountryID(ctx context.Context, countryID string, page *int, pageSize *int) (*models.RegionHTTPList, error) {
	atoi, err := strconv.Atoi(countryID)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": utils.ResponseError{
					Code:    http.StatusBadRequest,
					Message: consts.ErrAtoi,
				},
			},
		}
	}

	regions, countRows, err := r.regionService.GetRegionsByCountryId(uint(atoi), page, pageSize)
	if err != nil {
		r.loggers.Err.Printf("%s", err.Error())
		return nil, &gqlerror.Error{
			Extensions: map[string]interface{}{
				"err": err,
			},
		}
	}
	return &models.RegionHTTPList{
		Regions:   models.FromRegionsCore(regions),
		CountRows: int(countRows),
	}, nil
}
